services:
  web:
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver"
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web